
use ffi;

pub type FtResult<T> = Result<T, Error>;

#[deriving(Clone, PartialEq, Eq, Show)]
#[repr(i32)]
pub enum Error {
    Ok                          = ffi::FT_Err_Ok,
    CannotOpenResource          = ffi::FT_Err_Cannot_Open_Resource,
    UnknownFileFormat           = ffi::FT_Err_Unknown_File_Format,
    InvalidFileFormat           = ffi::FT_Err_Invalid_File_Format,
    InvalidVersion              = ffi::FT_Err_Invalid_Version,
    LowerModuleVersion          = ffi::FT_Err_Lower_Module_Version,
    InvalidArgument             = ffi::FT_Err_Invalid_Argument,
    UnimplementedFeature        = ffi::FT_Err_Unimplemented_Feature,
    InvalidTable                = ffi::FT_Err_Invalid_Table,
    InvalidOffset               = ffi::FT_Err_Invalid_Offset,
    ArrayTooLarge               = ffi::FT_Err_Array_Too_Large,
    MissingModule               = ffi::FT_Err_Missing_Module,
    MissingProperty             = ffi::FT_Err_Missing_Property,
    InvalidGlyphIndex           = ffi::FT_Err_Invalid_Glyph_Index,
    InvalidCharacterCode        = ffi::FT_Err_Invalid_Character_Code,
    InvalidGlyphFormat          = ffi::FT_Err_Invalid_Glyph_Format,
    CannotRenderGlyph           = ffi::FT_Err_Cannot_Render_Glyph,
    InvalidOutline              = ffi::FT_Err_Invalid_Outline,
    InvalidComposite            = ffi::FT_Err_Invalid_Composite,
    TooManyHints                = ffi::FT_Err_Too_Many_Hints,
    InvalidPixelSize            = ffi::FT_Err_Invalid_Pixel_Size,
    InvalidHandle               = ffi::FT_Err_Invalid_Handle,
    InvalidLibraryHandle        = ffi::FT_Err_Invalid_Library_Handle,
    InvalidDriverHandle         = ffi::FT_Err_Invalid_Driver_Handle,
    InvalidFaceHandle           = ffi::FT_Err_Invalid_Face_Handle,
    InvalidSizeHandle           = ffi::FT_Err_Invalid_Size_Handle,
    InvalidSlotHandle           = ffi::FT_Err_Invalid_Slot_Handle,
    InvalidCharMapHandle        = ffi::FT_Err_Invalid_CharMap_Handle,
    InvalidCacheHandle          = ffi::FT_Err_Invalid_Cache_Handle,
    InvalidStreamHandle         = ffi::FT_Err_Invalid_Stream_Handle,
    TooManyDrivers              = ffi::FT_Err_Too_Many_Drivers,
    TooManyExtensions           = ffi::FT_Err_Too_Many_Extensions,
    OutOfMemory                 = ffi::FT_Err_Out_Of_Memory,
    UnlistedObject              = ffi::FT_Err_Unlisted_Object,
    CannotOpenStream            = ffi::FT_Err_Cannot_Open_Stream,
    InvalidStreamSeek           = ffi::FT_Err_Invalid_Stream_Seek,
    InvalidStreamSkip           = ffi::FT_Err_Invalid_Stream_Skip,
    InvalidStreamRead           = ffi::FT_Err_Invalid_Stream_Read,
    InvalidStreamOperation      = ffi::FT_Err_Invalid_Stream_Operation,
    InvalidFrameOperation       = ffi::FT_Err_Invalid_Frame_Operation,
    NestedFrameAccess           = ffi::FT_Err_Nested_Frame_Access,
    InvalidFrameRead            = ffi::FT_Err_Invalid_Frame_Read,
    RasterUninitialized         = ffi::FT_Err_Raster_Uninitialized,
    RasterCorrupted             = ffi::FT_Err_Raster_Corrupted,
    RasterOverflow              = ffi::FT_Err_Raster_Overflow,
    RasterNegativeHeight        = ffi::FT_Err_Raster_Negative_Height,
    TooManyCaches               = ffi::FT_Err_Too_Many_Caches,
    InvalidOpcode               = ffi::FT_Err_Invalid_Opcode,
    TooFewArguments             = ffi::FT_Err_Too_Few_Arguments,
    StackOverflow               = ffi::FT_Err_Stack_Overflow,
    CodeOverflow                = ffi::FT_Err_Code_Overflow,
    BadArgument                 = ffi::FT_Err_Bad_Argument,
    DivideByZero                = ffi::FT_Err_Divide_By_Zero,
    InvalidReference            = ffi::FT_Err_Invalid_Reference,
    DebugOpCode                 = ffi::FT_Err_Debug_OpCode,
    ENDFInExecStream            = ffi::FT_Err_ENDF_In_Exec_Stream,
    NestedDEFS                  = ffi::FT_Err_Nested_DEFS,
    InvalidCodeRange            = ffi::FT_Err_Invalid_CodeRange,
    ExecutionTooLong            = ffi::FT_Err_Execution_Too_Long,
    TooManyFunctionDefs         = ffi::FT_Err_Too_Many_Function_Defs,
    TooManyInstructionDefs      = ffi::FT_Err_Too_Many_Instruction_Defs,
    TableMissing                = ffi::FT_Err_Table_Missing,
    HorizHeaderMissing          = ffi::FT_Err_Horiz_Header_Missing,
    LocationsMissing            = ffi::FT_Err_Locations_Missing,
    NameTableMissing            = ffi::FT_Err_Name_Table_Missing,
    CMapTableMissing            = ffi::FT_Err_CMap_Table_Missing,
    HmtxTableMissing            = ffi::FT_Err_Hmtx_Table_Missing,
    PostTableMissing            = ffi::FT_Err_Post_Table_Missing,
    InvalidHorizMetrics         = ffi::FT_Err_Invalid_Horiz_Metrics,
    InvalidCharMapFormat        = ffi::FT_Err_Invalid_CharMap_Format,
    InvalidPPem                 = ffi::FT_Err_Invalid_PPem,
    InvalidVertMetrics          = ffi::FT_Err_Invalid_Vert_Metrics,
    CouldNotFindContext         = ffi::FT_Err_Could_Not_Find_Context,
    InvalidPostTableFormat      = ffi::FT_Err_Invalid_Post_Table_Format,
    InvalidPostTable            = ffi::FT_Err_Invalid_Post_Table,
    SyntaxError                 = ffi::FT_Err_Syntax_Error,
    StackUnderflow              = ffi::FT_Err_Stack_Underflow,
    Ignore                      = ffi::FT_Err_Ignore,
    NoUnicodeGlyphName          = ffi::FT_Err_No_Unicode_Glyph_Name,
    MissingStartfontField       = ffi::FT_Err_Missing_Startfont_Field,
    MissingFontField            = ffi::FT_Err_Missing_Font_Field,
    MissingSizeField            = ffi::FT_Err_Missing_Size_Field,
    MissingFontboundingboxField = ffi::FT_Err_Missing_Fontboundingbox_Field,
    MissingCharsField           = ffi::FT_Err_Missing_Chars_Field,
    MissingStartcharField       = ffi::FT_Err_Missing_Startchar_Field,
    MissingEncodingField        = ffi::FT_Err_Missing_Encoding_Field,
    MissingBbxField             = ffi::FT_Err_Missing_Bbx_Field,
    BbxTooBig                   = ffi::FT_Err_Bbx_Too_Big,
    CorruptedFontHeader         = ffi::FT_Err_Corrupted_Font_Header,
    CorruptedFontGlyphs         = ffi::FT_Err_Corrupted_Font_Glyphs,
    Max                         = ffi::FT_Err_Max,
    UnknownError,
}

impl FromPrimitive for Error {
    fn from_i64(n: i64) -> Option<Error> {
        FromPrimitive::from_i32(n as i32)
    }

    fn from_u64(n: u64) -> Option<Error> {
        FromPrimitive::from_i32(n as i32)
    }

    #[allow(non_upper_case_globals)]
    fn from_i32(n: i32) -> Option<Error> {
        match n {
            ffi::FT_Err_Ok                            => Some(Ok),
            ffi::FT_Err_Cannot_Open_Resource          => Some(ffi::CannotOpenResource),
            ffi::FT_Err_Unknown_File_Format           => Some(ffi::UnknownFileFormat),
            ffi::FT_Err_Invalid_File_Format           => Some(ffi::InvalidFileFormat),
            ffi::FT_Err_Invalid_Version               => Some(ffi::InvalidVersion),
            ffi::FT_Err_Lower_Module_Version          => Some(ffi::LowerModuleVersion),
            ffi::FT_Err_Invalid_Argument              => Some(ffi::InvalidArgument),
            ffi::FT_Err_Unimplemented_Feature         => Some(ffi::UnimplementedFeature),
            ffi::FT_Err_Invalid_Table                 => Some(ffi::InvalidTable),
            ffi::FT_Err_Invalid_Offset                => Some(ffi::InvalidOffset),
            ffi::FT_Err_Array_Too_Large               => Some(ffi::ArrayTooLarge),
            ffi::FT_Err_Missing_Module                => Some(ffi::MissingModule),
            ffi::FT_Err_Missing_Property              => Some(ffi::MissingProperty),
            ffi::FT_Err_Invalid_Glyph_Index           => Some(ffi::InvalidGlyphIndex),
            ffi::FT_Err_Invalid_Character_Code        => Some(ffi::InvalidCharacterCode),
            ffi::FT_Err_Invalid_Glyph_Format          => Some(ffi::InvalidGlyphFormat),
            ffi::FT_Err_Cannot_Render_Glyph           => Some(ffi::CannotRenderGlyph),
            ffi::FT_Err_Invalid_Outline               => Some(ffi::InvalidOutline),
            ffi::FT_Err_Invalid_Composite             => Some(ffi::InvalidComposite),
            ffi::FT_Err_Too_Many_Hints                => Some(ffi::TooManyHints),
            ffi::FT_Err_Invalid_Pixel_Size            => Some(ffi::InvalidPixelSize),
            ffi::FT_Err_Invalid_Handle                => Some(ffi::InvalidHandle),
            ffi::FT_Err_Invalid_Library_Handle        => Some(ffi::InvalidLibraryHandle),
            ffi::FT_Err_Invalid_Driver_Handle         => Some(ffi::InvalidDriverHandle),
            ffi::FT_Err_Invalid_Face_Handle           => Some(ffi::InvalidFaceHandle),
            ffi::FT_Err_Invalid_Size_Handle           => Some(ffi::InvalidSizeHandle),
            ffi::FT_Err_Invalid_Slot_Handle           => Some(ffi::InvalidSlotHandle),
            ffi::FT_Err_Invalid_CharMap_Handle        => Some(ffi::InvalidCharMapHandle),
            ffi::FT_Err_Invalid_Cache_Handle          => Some(ffi::InvalidCacheHandle),
            ffi::FT_Err_Invalid_Stream_Handle         => Some(ffi::InvalidStreamHandle),
            ffi::FT_Err_Too_Many_Drivers              => Some(ffi::TooManyDrivers),
            ffi::FT_Err_Too_Many_Extensions           => Some(ffi::TooManyExtensions),
            ffi::FT_Err_Out_Of_Memory                 => Some(ffi::OutOfMemory),
            ffi::FT_Err_Unlisted_Object               => Some(ffi::UnlistedObject),
            ffi::FT_Err_Cannot_Open_Stream            => Some(ffi::CannotOpenStream),
            ffi::FT_Err_Invalid_Stream_Seek           => Some(ffi::InvalidStreamSeek),
            ffi::FT_Err_Invalid_Stream_Skip           => Some(ffi::InvalidStreamSkip),
            ffi::FT_Err_Invalid_Stream_Read           => Some(ffi::InvalidStreamRead),
            ffi::FT_Err_Invalid_Stream_Operation      => Some(ffi::InvalidStreamOperation),
            ffi::FT_Err_Invalid_Frame_Operation       => Some(ffi::InvalidFrameOperation),
            ffi::FT_Err_Nested_Frame_Access           => Some(ffi::NestedFrameAccess),
            ffi::FT_Err_Invalid_Frame_Read            => Some(ffi::InvalidFrameRead),
            ffi::FT_Err_Raster_Uninitialized          => Some(ffi::RasterUninitialized),
            ffi::FT_Err_Raster_Corrupted              => Some(ffi::RasterCorrupted),
            ffi::FT_Err_Raster_Overflow               => Some(ffi::RasterOverflow),
            ffi::FT_Err_Raster_Negative_Height        => Some(ffi::RasterNegativeHeight),
            ffi::FT_Err_Too_Many_Caches               => Some(ffi::TooManyCaches),
            ffi::FT_Err_Invalid_Opcode                => Some(ffi::InvalidOpcode),
            ffi::FT_Err_Too_Few_Arguments             => Some(ffi::TooFewArguments),
            ffi::FT_Err_Stack_Overflow                => Some(ffi::StackOverflow),
            ffi::FT_Err_Code_Overflow                 => Some(ffi::CodeOverflow),
            ffi::FT_Err_Bad_Argument                  => Some(ffi::BadArgument),
            ffi::FT_Err_Divide_By_Zero                => Some(ffi::DivideByZero),
            ffi::FT_Err_Invalid_Reference             => Some(ffi::InvalidReference),
            ffi::FT_Err_Debug_OpCode                  => Some(ffi::DebugOpCode),
            ffi::FT_Err_ENDF_In_Exec_Stream           => Some(ffi::ENDFInExecStream),
            ffi::FT_Err_Nested_DEFS                   => Some(ffi::NestedDEFS),
            ffi::FT_Err_Invalid_CodeRange             => Some(ffi::InvalidCodeRange),
            ffi::FT_Err_Execution_Too_Long            => Some(ffi::ExecutionTooLong),
            ffi::FT_Err_Too_Many_Function_Defs        => Some(ffi::TooManyFunctionDefs),
            ffi::FT_Err_Too_Many_Instruction_Defs     => Some(ffi::TooManyInstructionDefs),
            ffi::FT_Err_Table_Missing                 => Some(ffi::TableMissing),
            ffi::FT_Err_Horiz_Header_Missing          => Some(ffi::HorizHeaderMissing),
            ffi::FT_Err_Locations_Missing             => Some(ffi::LocationsMissing),
            ffi::FT_Err_Name_Table_Missing            => Some(ffi::NameTableMissing),
            ffi::FT_Err_CMap_Table_Missing            => Some(ffi::CMapTableMissing),
            ffi::FT_Err_Hmtx_Table_Missing            => Some(ffi::HmtxTableMissing),
            ffi::FT_Err_Post_Table_Missing            => Some(ffi::PostTableMissing),
            ffi::FT_Err_Invalid_Horiz_Metrics         => Some(ffi::InvalidHorizMetrics),
            ffi::FT_Err_Invalid_CharMap_Format        => Some(ffi::InvalidCharMapFormat),
            ffi::FT_Err_Invalid_PPem                  => Some(ffi::InvalidPPem),
            ffi::FT_Err_Invalid_Vert_Metrics          => Some(ffi::InvalidVertMetrics),
            ffi::FT_Err_Could_Not_Find_Context        => Some(ffi::CouldNotFindContext),
            ffi::FT_Err_Invalid_Post_Table_Format     => Some(ffi::InvalidPostTableFormat),
            ffi::FT_Err_Invalid_Post_Table            => Some(ffi::InvalidPostTable),
            ffi::FT_Err_Syntax_Error                  => Some(ffi::SyntaxError),
            ffi::FT_Err_Stack_Underflow               => Some(ffi::StackUnderflow),
            ffi::FT_Err_Ignore                        => Some(ffi::Ignore),
            ffi::FT_Err_No_Unicode_Glyph_Name         => Some(ffi::NoUnicodeGlyphName),
            ffi::FT_Err_Missing_Startfont_Field       => Some(ffi::MissingStartfontField),
            ffi::FT_Err_Missing_Font_Field            => Some(ffi::MissingFontField),
            ffi::FT_Err_Missing_Size_Field            => Some(ffi::MissingSizeField),
            ffi::FT_Err_Missing_Fontboundingbox_Field => Some(ffi::MissingFontboundingboxField),
            ffi::FT_Err_Missing_Chars_Field           => Some(ffi::MissingCharsField),
            ffi::FT_Err_Missing_Startchar_Field       => Some(ffi::MissingStartcharField),
            ffi::FT_Err_Missing_Encoding_Field        => Some(ffi::MissingEncodingField),
            ffi::FT_Err_Missing_Bbx_Field             => Some(ffi::MissingBbxField),
            ffi::FT_Err_Bbx_Too_Big                   => Some(ffi::BbxTooBig),
            ffi::FT_Err_Corrupted_Font_Header         => Some(ffi::CorruptedFontHeader),
            ffi::FT_Err_Corrupted_Font_Glyphs         => Some(ffi::CorruptedFontGlyphs),
            ffi::FT_Err_Max                           => Some(ffi::Max),
            _ => Some(ffi::UnknownError),
        }
    }
}

