
use ffi;

pub type FtResult<T> = Result<T, Error>;

#[deriving(Clone, PartialEq, Eq, Show)]
#[repr(i32)]
pub enum Error {
    Ok                          = ffi::FT_Err_Ok,
    CannotOpenResource          = ffi::FT_Err_Cannot_Open_Resource,
    UnknownFileFormat           = ffi::FT_Err_Unknown_File_Format,
    InvalidFileFormat           = ffi::FT_Err_Invalid_File_Format,
    InvalidVersion              = ffi::FT_Err_Invalid_Version,
    LowerModuleVersion          = ffi::FT_Err_Lower_Module_Version,
    InvalidArgument             = ffi::FT_Err_Invalid_Argument,
    UnimplementedFeature        = ffi::FT_Err_Unimplemented_Feature,
    InvalidTable                = ffi::FT_Err_Invalid_Table,
    InvalidOffset               = ffi::FT_Err_Invalid_Offset,
    ArrayTooLarge               = ffi::FT_Err_Array_Too_Large,
    MissingModule               = ffi::FT_Err_Missing_Module,
    MissingProperty             = ffi::FT_Err_Missing_Property,
    InvalidGlyphIndex           = ffi::FT_Err_Invalid_Glyph_Index,
    InvalidCharacterCode        = ffi::FT_Err_Invalid_Character_Code,
    InvalidGlyphFormat          = ffi::FT_Err_Invalid_Glyph_Format,
    CannotRenderGlyph           = ffi::FT_Err_Cannot_Render_Glyph,
    InvalidOutline              = ffi::FT_Err_Invalid_Outline,
    InvalidComposite            = ffi::FT_Err_Invalid_Composite,
    TooManyHints                = ffi::FT_Err_Too_Many_Hints,
    InvalidPixelSize            = ffi::FT_Err_Invalid_Pixel_Size,
    InvalidHandle               = ffi::FT_Err_Invalid_Handle,
    InvalidLibraryHandle        = ffi::FT_Err_Invalid_Library_Handle,
    InvalidDriverHandle         = ffi::FT_Err_Invalid_Driver_Handle,
    InvalidFaceHandle           = ffi::FT_Err_Invalid_Face_Handle,
    InvalidSizeHandle           = ffi::FT_Err_Invalid_Size_Handle,
    InvalidSlotHandle           = ffi::FT_Err_Invalid_Slot_Handle,
    InvalidCharMapHandle        = ffi::FT_Err_Invalid_CharMap_Handle,
    InvalidCacheHandle          = ffi::FT_Err_Invalid_Cache_Handle,
    InvalidStreamHandle         = ffi::FT_Err_Invalid_Stream_Handle,
    TooManyDrivers              = ffi::FT_Err_Too_Many_Drivers,
    TooManyExtensions           = ffi::FT_Err_Too_Many_Extensions,
    OutOfMemory                 = ffi::FT_Err_Out_Of_Memory,
    UnlistedObject              = ffi::FT_Err_Unlisted_Object,
    CannotOpenStream            = ffi::FT_Err_Cannot_Open_Stream,
    InvalidStreamSeek           = ffi::FT_Err_Invalid_Stream_Seek,
    InvalidStreamSkip           = ffi::FT_Err_Invalid_Stream_Skip,
    InvalidStreamRead           = ffi::FT_Err_Invalid_Stream_Read,
    InvalidStreamOperation      = ffi::FT_Err_Invalid_Stream_Operation,
    InvalidFrameOperation       = ffi::FT_Err_Invalid_Frame_Operation,
    NestedFrameAccess           = ffi::FT_Err_Nested_Frame_Access,
    InvalidFrameRead            = ffi::FT_Err_Invalid_Frame_Read,
    RasterUninitialized         = ffi::FT_Err_Raster_Uninitialized,
    RasterCorrupted             = ffi::FT_Err_Raster_Corrupted,
    RasterOverflow              = ffi::FT_Err_Raster_Overflow,
    RasterNegativeHeight        = ffi::FT_Err_Raster_Negative_Height,
    TooManyCaches               = ffi::FT_Err_Too_Many_Caches,
    InvalidOpcode               = ffi::FT_Err_Invalid_Opcode,
    TooFewArguments             = ffi::FT_Err_Too_Few_Arguments,
    StackOverflow               = ffi::FT_Err_Stack_Overflow,
    CodeOverflow                = ffi::FT_Err_Code_Overflow,
    BadArgument                 = ffi::FT_Err_Bad_Argument,
    DivideByZero                = ffi::FT_Err_Divide_By_Zero,
    InvalidReference            = ffi::FT_Err_Invalid_Reference,
    DebugOpCode                 = ffi::FT_Err_Debug_OpCode,
    ENDFInExecStream            = ffi::FT_Err_ENDF_In_Exec_Stream,
    NestedDEFS                  = ffi::FT_Err_Nested_DEFS,
    InvalidCodeRange            = ffi::FT_Err_Invalid_CodeRange,
    ExecutionTooLong            = ffi::FT_Err_Execution_Too_Long,
    TooManyFunctionDefs         = ffi::FT_Err_Too_Many_Function_Defs,
    TooManyInstructionDefs      = ffi::FT_Err_Too_Many_Instruction_Defs,
    TableMissing                = ffi::FT_Err_Table_Missing,
    HorizHeaderMissing          = ffi::FT_Err_Horiz_Header_Missing,
    LocationsMissing            = ffi::FT_Err_Locations_Missing,
    NameTableMissing            = ffi::FT_Err_Name_Table_Missing,
    CMapTableMissing            = ffi::FT_Err_CMap_Table_Missing,
    HmtxTableMissing            = ffi::FT_Err_Hmtx_Table_Missing,
    PostTableMissing            = ffi::FT_Err_Post_Table_Missing,
    InvalidHorizMetrics         = ffi::FT_Err_Invalid_Horiz_Metrics,
    InvalidCharMapFormat        = ffi::FT_Err_Invalid_CharMap_Format,
    InvalidPPem                 = ffi::FT_Err_Invalid_PPem,
    InvalidVertMetrics          = ffi::FT_Err_Invalid_Vert_Metrics,
    CouldNotFindContext         = ffi::FT_Err_Could_Not_Find_Context,
    InvalidPostTableFormat      = ffi::FT_Err_Invalid_Post_Table_Format,
    InvalidPostTable            = ffi::FT_Err_Invalid_Post_Table,
    SyntaxError                 = ffi::FT_Err_Syntax_Error,
    StackUnderflow              = ffi::FT_Err_Stack_Underflow,
    Ignore                      = ffi::FT_Err_Ignore,
    NoUnicodeGlyphName          = ffi::FT_Err_No_Unicode_Glyph_Name,
    MissingStartfontField       = ffi::FT_Err_Missing_Startfont_Field,
    MissingFontField            = ffi::FT_Err_Missing_Font_Field,
    MissingSizeField            = ffi::FT_Err_Missing_Size_Field,
    MissingFontboundingboxField = ffi::FT_Err_Missing_Fontboundingbox_Field,
    MissingCharsField           = ffi::FT_Err_Missing_Chars_Field,
    MissingStartcharField       = ffi::FT_Err_Missing_Startchar_Field,
    MissingEncodingField        = ffi::FT_Err_Missing_Encoding_Field,
    MissingBbxField             = ffi::FT_Err_Missing_Bbx_Field,
    BbxTooBig                   = ffi::FT_Err_Bbx_Too_Big,
    CorruptedFontHeader         = ffi::FT_Err_Corrupted_Font_Header,
    CorruptedFontGlyphs         = ffi::FT_Err_Corrupted_Font_Glyphs,
    Max                         = ffi::FT_Err_Max,
    UnknownError,
}

impl FromPrimitive for Error {
    fn from_i64(n: i64) -> Option<Error> {
        FromPrimitive::from_i32(n as i32)
    }

    fn from_u64(n: u64) -> Option<Error> {
        FromPrimitive::from_i32(n as i32)
    }

    #[allow(non_uppercase_statics)]
    fn from_i32(n: i32) -> Option<Error> {
        match n {
            ffi::FT_Err_Ok                            => Some(Ok),
            ffi::FT_Err_Cannot_Open_Resource          => Some(CannotOpenResource),
            ffi::FT_Err_Unknown_File_Format           => Some(UnknownFileFormat),
            ffi::FT_Err_Invalid_File_Format           => Some(InvalidFileFormat),
            ffi::FT_Err_Invalid_Version               => Some(InvalidVersion),
            ffi::FT_Err_Lower_Module_Version          => Some(LowerModuleVersion),
            ffi::FT_Err_Invalid_Argument              => Some(InvalidArgument),
            ffi::FT_Err_Unimplemented_Feature         => Some(UnimplementedFeature),
            ffi::FT_Err_Invalid_Table                 => Some(InvalidTable),
            ffi::FT_Err_Invalid_Offset                => Some(InvalidOffset),
            ffi::FT_Err_Array_Too_Large               => Some(ArrayTooLarge),
            ffi::FT_Err_Missing_Module                => Some(MissingModule),
            ffi::FT_Err_Missing_Property              => Some(MissingProperty),
            ffi::FT_Err_Invalid_Glyph_Index           => Some(InvalidGlyphIndex),
            ffi::FT_Err_Invalid_Character_Code        => Some(InvalidCharacterCode),
            ffi::FT_Err_Invalid_Glyph_Format          => Some(InvalidGlyphFormat),
            ffi::FT_Err_Cannot_Render_Glyph           => Some(CannotRenderGlyph),
            ffi::FT_Err_Invalid_Outline               => Some(InvalidOutline),
            ffi::FT_Err_Invalid_Composite             => Some(InvalidComposite),
            ffi::FT_Err_Too_Many_Hints                => Some(TooManyHints),
            ffi::FT_Err_Invalid_Pixel_Size            => Some(InvalidPixelSize),
            ffi::FT_Err_Invalid_Handle                => Some(InvalidHandle),
            ffi::FT_Err_Invalid_Library_Handle        => Some(InvalidLibraryHandle),
            ffi::FT_Err_Invalid_Driver_Handle         => Some(InvalidDriverHandle),
            ffi::FT_Err_Invalid_Face_Handle           => Some(InvalidFaceHandle),
            ffi::FT_Err_Invalid_Size_Handle           => Some(InvalidSizeHandle),
            ffi::FT_Err_Invalid_Slot_Handle           => Some(InvalidSlotHandle),
            ffi::FT_Err_Invalid_CharMap_Handle        => Some(InvalidCharMapHandle),
            ffi::FT_Err_Invalid_Cache_Handle          => Some(InvalidCacheHandle),
            ffi::FT_Err_Invalid_Stream_Handle         => Some(InvalidStreamHandle),
            ffi::FT_Err_Too_Many_Drivers              => Some(TooManyDrivers),
            ffi::FT_Err_Too_Many_Extensions           => Some(TooManyExtensions),
            ffi::FT_Err_Out_Of_Memory                 => Some(OutOfMemory),
            ffi::FT_Err_Unlisted_Object               => Some(UnlistedObject),
            ffi::FT_Err_Cannot_Open_Stream            => Some(CannotOpenStream),
            ffi::FT_Err_Invalid_Stream_Seek           => Some(InvalidStreamSeek),
            ffi::FT_Err_Invalid_Stream_Skip           => Some(InvalidStreamSkip),
            ffi::FT_Err_Invalid_Stream_Read           => Some(InvalidStreamRead),
            ffi::FT_Err_Invalid_Stream_Operation      => Some(InvalidStreamOperation),
            ffi::FT_Err_Invalid_Frame_Operation       => Some(InvalidFrameOperation),
            ffi::FT_Err_Nested_Frame_Access           => Some(NestedFrameAccess),
            ffi::FT_Err_Invalid_Frame_Read            => Some(InvalidFrameRead),
            ffi::FT_Err_Raster_Uninitialized          => Some(RasterUninitialized),
            ffi::FT_Err_Raster_Corrupted              => Some(RasterCorrupted),
            ffi::FT_Err_Raster_Overflow               => Some(RasterOverflow),
            ffi::FT_Err_Raster_Negative_Height        => Some(RasterNegativeHeight),
            ffi::FT_Err_Too_Many_Caches               => Some(TooManyCaches),
            ffi::FT_Err_Invalid_Opcode                => Some(InvalidOpcode),
            ffi::FT_Err_Too_Few_Arguments             => Some(TooFewArguments),
            ffi::FT_Err_Stack_Overflow                => Some(StackOverflow),
            ffi::FT_Err_Code_Overflow                 => Some(CodeOverflow),
            ffi::FT_Err_Bad_Argument                  => Some(BadArgument),
            ffi::FT_Err_Divide_By_Zero                => Some(DivideByZero),
            ffi::FT_Err_Invalid_Reference             => Some(InvalidReference),
            ffi::FT_Err_Debug_OpCode                  => Some(DebugOpCode),
            ffi::FT_Err_ENDF_In_Exec_Stream           => Some(ENDFInExecStream),
            ffi::FT_Err_Nested_DEFS                   => Some(NestedDEFS),
            ffi::FT_Err_Invalid_CodeRange             => Some(InvalidCodeRange),
            ffi::FT_Err_Execution_Too_Long            => Some(ExecutionTooLong),
            ffi::FT_Err_Too_Many_Function_Defs        => Some(TooManyFunctionDefs),
            ffi::FT_Err_Too_Many_Instruction_Defs     => Some(TooManyInstructionDefs),
            ffi::FT_Err_Table_Missing                 => Some(TableMissing),
            ffi::FT_Err_Horiz_Header_Missing          => Some(HorizHeaderMissing),
            ffi::FT_Err_Locations_Missing             => Some(LocationsMissing),
            ffi::FT_Err_Name_Table_Missing            => Some(NameTableMissing),
            ffi::FT_Err_CMap_Table_Missing            => Some(CMapTableMissing),
            ffi::FT_Err_Hmtx_Table_Missing            => Some(HmtxTableMissing),
            ffi::FT_Err_Post_Table_Missing            => Some(PostTableMissing),
            ffi::FT_Err_Invalid_Horiz_Metrics         => Some(InvalidHorizMetrics),
            ffi::FT_Err_Invalid_CharMap_Format        => Some(InvalidCharMapFormat),
            ffi::FT_Err_Invalid_PPem                  => Some(InvalidPPem),
            ffi::FT_Err_Invalid_Vert_Metrics          => Some(InvalidVertMetrics),
            ffi::FT_Err_Could_Not_Find_Context        => Some(CouldNotFindContext),
            ffi::FT_Err_Invalid_Post_Table_Format     => Some(InvalidPostTableFormat),
            ffi::FT_Err_Invalid_Post_Table            => Some(InvalidPostTable),
            ffi::FT_Err_Syntax_Error                  => Some(SyntaxError),
            ffi::FT_Err_Stack_Underflow               => Some(StackUnderflow),
            ffi::FT_Err_Ignore                        => Some(Ignore),
            ffi::FT_Err_No_Unicode_Glyph_Name         => Some(NoUnicodeGlyphName),
            ffi::FT_Err_Missing_Startfont_Field       => Some(MissingStartfontField),
            ffi::FT_Err_Missing_Font_Field            => Some(MissingFontField),
            ffi::FT_Err_Missing_Size_Field            => Some(MissingSizeField),
            ffi::FT_Err_Missing_Fontboundingbox_Field => Some(MissingFontboundingboxField),
            ffi::FT_Err_Missing_Chars_Field           => Some(MissingCharsField),
            ffi::FT_Err_Missing_Startchar_Field       => Some(MissingStartcharField),
            ffi::FT_Err_Missing_Encoding_Field        => Some(MissingEncodingField),
            ffi::FT_Err_Missing_Bbx_Field             => Some(MissingBbxField),
            ffi::FT_Err_Bbx_Too_Big                   => Some(BbxTooBig),
            ffi::FT_Err_Corrupted_Font_Header         => Some(CorruptedFontHeader),
            ffi::FT_Err_Corrupted_Font_Glyphs         => Some(CorruptedFontGlyphs),
            ffi::FT_Err_Max                           => Some(Max),
            _ => Some(UnknownError),
        }
    }
}

